### ISSUE TITLE
MultiFeed 

### ISSUE THREAD

**Issue by lmacret** [inpsyde/WP-Multisite-Feed#13]
hello 
great plugin, it almost do what i need :) 
But my need is to make more than one feed. one feed with some blogs of the network, another feed with others blogs

do you think it is possible in a nearly future ?

**Comment by bueltge** [comment]
What you define with 'another feed with other blogs'? Currently create the plugin one feed for all public blogs of the network.

**Comment by lmacret** [comment]
Yeah but my need, is create one feed with a selection of public bogs, and one feed with another selection (by example, first feed with men bloggers, one feed with women bloggers) :)

**Comment by lmacret** [comment]
Nevermind, found a trick to do what i want, will use a multi-network of multi-site :) so powerful, and will use you plugin :) thx a lot

**Comment by bueltge** [comment]
Welcome.
