### ISSUE TITLE
Cannot create feed

### ISSUE THREAD

**Issue by Bellfalasch** [inpsyde/wp-multisite-feed#15]
Hi, I love the idea of this plugin, just what I need. I have 20 sites in my multisite install, I install the plugin and configure it to output my new mutlifeed. After I click save the page reloads and the form is empty. I cannot see anything is saved. Tried changing multiple values, still same thing happens.

I have the iThemes Security plugin, but turning it off didn't help. Any suggestions? I haven't found any other plugin that does this thing the same way you do so would really love for it to work.

I'm using latest version of plugin, latest WP, but running PHP 5.6.

**Comment by bueltge** [comment]
We close this repo and do not support it.
