### ISSUE TITLE
[Bug]: Yoast >19.2 conflict 

### ISSUE THREAD

**Issue by cagdasdag** [inpsyde/wp-multisite-feed#28]
### Description of the bug

We are using get_bloginfo_rss filter like this: 
`$title = apply_filters( 'get_bloginfo_rss', convert_chars( $info ) );`

But after 19.2 version of Yoast, they have a code like this:
`\add_filter( 'get_bloginfo_rss', [ $this, 'filter_bloginfo_rss' ], 10, 2 );`

That's why we are getting 
`Uncaught ArgumentCountError: Too few arguments to function Yoast\WP\SEO\Integrations\Front_End\Feed_Improvements::filter_bloginfo_rss(), 1 passed in` fatal error. 

As the filter itself has 2 parameter: 
https://developer.wordpress.org/reference/hooks/get_bloginfo_rss/

We should change our usage that use both parameter. 

### Reproduction instructions

1. Install >19.2 version of Yoast
2. Install multisite-feed plugin
3. Go to multifeed url 
4. You will see fatal error there. 

### Expected behavior

It should work without fatal error. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bueltge** [comment]
Thanks a lot, @cagdasdag for the note and the PR with a fix, there are merged now, and also released.
