### ISSUE TITLE
Two Features

### ISSUE THREAD

**Issue by inoatech** [inpsyde/WP-Multisite-Feed#5]
I'm a happy user of this plugin - thanks!
Two features I would love to see:

1. Inclusion of Blog title in additional element in RSS feed
2. Option to pull first image or feature image post into additional RSS element

**Comment by bueltge** [comment]
Thanks for usage of our plugin and also thanks for the ideas.
I have switched this 2 issues in 2 issues to map it better to development.
Maybe you see on this issues and you have additional information. Currently I haven't a idea, which element in the RSS2 format are the right tag.

Best regards
