### ISSUE TITLE
Option to pull first image or feature image post into additional RSS element

### ISSUE THREAD

**Issue by bueltge** [inpsyde/wp-multisite-feed#6]
Questions:
- Which RSS2 element? 

via https://github.com/inoatech

**Comment by inoatech** [comment]
This could simply show up as <image>: http://cyber.law.harvard.edu/rss/rss.html#ltimagegtSubelementOfLtchannelgt

It has three required sub-elements: <url> <link> and <title>. Title and link could be the same as for the post as a whole. <url> would point to the image.

Thanks.

**Comment by bueltge** [comment]
@inoatech image and site title now inside the feed. Please can you test, maybe also with feed readers. A small hint from my side, if I understand this correctly. The image tag is a subtag from `channel`, not a subtag of each `item`. Maybe this is a problem for readers.

**Comment by bueltge** [comment]
Maybe helpful, the `media` tag.
`<media:thumbnail url='http://www.imagepath.jpg' height='75' width='75' />`
