### ISSUE TITLE
Inclusion of Blog title in additional element in RSS feed

### ISSUE THREAD

**Issue by bueltge** [inpsyde/WP-Multisite-Feed#7]
Which RSS2 tag is the right for this title of each blog?

via https://github.com/inoatech

**Comment by inoatech** [comment]
Within the RSS2 specification, I think "category" would make the most sense for this. (The actual categories of each post is somewhat irrelevant when all the posts are aggregated, and I don't think it's too much of a stretch to conceive of individual blogs as categories. This also allows filters by category, which seems very appropriate.)

Further afield, Atom is more flexible, and the various metadata extensions may offer other ways to do this, but makes sense it keep it simple and just RSS2 for now.
