### ISSUE TITLE
'use_excerpt' setting is ambiguous

### ISSUE THREAD

**Issue by Biont** [inpsyde/WP-Multisite-Feed#8]
The setting might suggest that it enables users to use the post excerpt in `<content:encoded>`.

Both the text label "Full Feed" / "Ganzer Text" as well as the naming of the setting itself (`use_excerpt`) support that interpretation

On closer inspection, though, it actually controls the `$more` global that is used to determine whether to render the full post_content, or only the part before the `<!---more--->` tag.

There is currently no way to use excerpts in feeds, which is an option that is available for core feeds via _Options > Reading_

My suggestion would be to rename that option to something like `show_more` and actually implement the usage of post excerpts in the plugin

**Comment by bueltge** [comment]
The current implementation use the excerpt. The excerpt is a custom meta field on each post and if is empty, WP core add on default the first x words from the main content. However if you fill the excerpt meta data, you get also this content from the meta data. 
So I mean the description is ok?

**Comment by Biont** [comment]
Yes, this looks okay now. Maybe I implemented that at some point and forgot to update this issue @bueltge .
I'll go ahead and close here.
